export interface SchemaField {
  name: string;
  type: string;
  isPk?: boolean;
  isFk?: boolean;
  fkTarget?: string;
  description: string;
}

export interface SchemaTable {
  id: string;
  name: string;
  description: string;
  fields: SchemaField[];
  relationships: string[];
}

export const DB_TABLES: SchemaTable[] = [
  {
    id: "wallet",
    name: "Wallet",
    description: "Stores unique Bitcoin address entities, address classifications, and aggregated graph features.",
    fields: [
      { name: "address", type: "VARCHAR(64)", isPk: true, description: "Unique Bitcoin address (Base58 or Bech32)" },
      { name: "address_type", type: "VARCHAR(16)", description: "Legacy (P2PKH), P2SH, or Bech32 SegWit" },
      { name: "first_seen", type: "TIMESTAMP", description: "First recorded transaction timestamp" },
      { name: "last_seen", type: "TIMESTAMP", description: "Most recent activity timestamp" },
      { name: "total_in_btc", type: "NUMERIC(18,8)", description: "Cumulative incoming Bitcoin volume" },
      { name: "total_out_btc", type: "NUMERIC(18,8)", description: "Cumulative outgoing Bitcoin volume" },
      { name: "current_balance", type: "NUMERIC(18,8)", description: "Current unspent UTXO balance" },
      { name: "pagerank", type: "FLOAT", description: "Graph network centrality PageRank score" },
      { name: "out_degree", type: "INTEGER", description: "Number of unique recipient outgoing edges" },
      { name: "in_degree", type: "INTEGER", description: "Number of unique sender incoming edges" },
      { name: "entity_cluster_id", type: "VARCHAR(32)", description: "DBSCAN assigned criminal syndicate cluster" }
    ],
    relationships: [
      "1:N with Transaction (as source_wallet or dest_wallet)",
      "1:N with Alert (flagged entity alerts)",
      "M:N with IP (via transaction relay broadcasts)"
    ]
  },
  {
    id: "transaction",
    name: "Transaction",
    description: "Immutable Bitcoin ledger transfer records containing input/output UTXOs and fee metadata.",
    fields: [
      { name: "tx_hash", type: "VARCHAR(64)", isPk: true, description: "SHA-256 double-hash transaction identifier" },
      { name: "src_wallet", type: "VARCHAR(64)", isFk: true, fkTarget: "Wallet.address", description: "Broadcasting sender address" },
      { name: "dst_wallet", type: "VARCHAR(64)", isFk: true, fkTarget: "Wallet.address", description: "Recipient output address" },
      { name: "amount_satoshis", type: "BIGINT", description: "Transfer value in Satoshis (1 BTC = 10^8 sats)" },
      { name: "amount_btc", type: "NUMERIC(18,8)", description: "Standardized decimal Bitcoin amount" },
      { name: "fee_satoshis", type: "INTEGER", description: "Miner transaction inclusion fee" },
      { name: "block_height", type: "INTEGER", description: "Bitcoin block height ledger confirmation" },
      { name: "timestamp", type: "TIMESTAMP", description: "Block inclusion UTC timestamp" },
      { name: "is_peel_chain", type: "BOOLEAN", description: "Flagged as high-volume peel split hop" },
      { name: "session_id", type: "VARCHAR(36)", isFk: true, fkTarget: "Session.session_id", description: "Investigation ingest batch ID" }
    ],
    relationships: [
      "N:1 with Wallet (source and destination)",
      "1:N with IP (relayed through broadcast nodes)",
      "N:1 with Session (ingestion batch)"
    ]
  },
  {
    id: "ip",
    name: "IP",
    description: "Network layer telemetry capturing peer broadcast IPs, ASNs, and privacy tooling indicators.",
    fields: [
      { name: "ip_address", type: "VARCHAR(45)", isPk: true, description: "IPv4 or IPv6 broadcaster address" },
      { name: "country_code", type: "VARCHAR(3)", description: "ISO 3166-1 alpha-2 geographical country code" },
      { name: "city", type: "VARCHAR(64)", description: "City resolved via GeoIP database" },
      { name: "asn", type: "VARCHAR(64)", description: "Autonomous System Number and ISP organization" },
      { name: "is_tor_exit", type: "BOOLEAN", description: "Matched against active Tor exit node directory" },
      { name: "is_vpn", type: "BOOLEAN", description: "Classified as commercial VPN / proxy service" },
      { name: "threat_score", type: "INTEGER", description: "IP reputation threat index (0-100)" }
    ],
    relationships: [
      "M:N with Transaction (via broadcast peer correlation)",
      "1:N with Alert (suspicious IP origin alerts)"
    ]
  },
  {
    id: "alert",
    name: "Alert",
    description: "High-priority forensic alerts generated by the AI detection and explainability engines.",
    fields: [
      { name: "alert_id", type: "VARCHAR(36)", isPk: true, description: "UUID primary key" },
      { name: "wallet_address", type: "VARCHAR(64)", isFk: true, fkTarget: "Wallet.address", description: "Subject target wallet address" },
      { name: "risk_score", type: "FLOAT", description: "Final composite risk percentage (0.0 to 100.0)" },
      { name: "confidence", type: "FLOAT", description: "Statistical confidence metric (0.0 to 100.0)" },
      { name: "threat_level", type: "VARCHAR(16)", description: "CRITICAL | HIGH | MEDIUM | LOW" },
      { name: "reasons", type: "JSONB", description: "Structured checklist of explainable forensic reasons" },
      { name: "shap_values", type: "JSONB", description: "Feature attribution vector weights" },
      { name: "status", type: "VARCHAR(24)", description: "NEW | IN_REVIEW | ESCALATED | CLOSED" },
      { name: "created_at", type: "TIMESTAMP", description: "Alert trigger creation timestamp" }
    ],
    relationships: [
      "N:1 with Wallet",
      "N:1 with Analysis (generated from ML analysis run)"
    ]
  },
  {
    id: "analysis",
    name: "Analysis",
    description: "Metadata and hyperparameters for specific machine learning and graph calculation runs.",
    fields: [
      { name: "analysis_id", type: "VARCHAR(36)", isPk: true, description: "Unique analysis run identifier" },
      { name: "session_id", type: "VARCHAR(36)", isFk: true, fkTarget: "Session.session_id", description: "Associated dataset session" },
      { name: "model_type", type: "VARCHAR(32)", description: "IsolationForest + DBSCAN + Heuristics" },
      { name: "contamination_rate", type: "FLOAT", description: "Configured anomaly contamination ratio" },
      { name: "total_nodes_processed", type: "INTEGER", description: "Graph node count at execution" },
      { name: "total_edges_processed", type: "INTEGER", description: "Graph edge count at execution" },
      { name: "execution_time_seconds", type: "FLOAT", description: "Pipeline runtime duration in seconds" },
      { name: "completed_at", type: "TIMESTAMP", description: "Analysis completion timestamp" }
    ],
    relationships: [
      "1:N with Alert",
      "N:1 with Session"
    ]
  },
  {
    id: "session",
    name: "Session",
    description: "User investigation workspace session managing dataset ingestion and case dossiers.",
    fields: [
      { name: "session_id", type: "VARCHAR(36)", isPk: true, description: "UUID session identifier" },
      { name: "investigator_name", type: "VARCHAR(64)", description: "Assigned cyber investigator / SIH team" },
      { name: "dataset_name", type: "VARCHAR(128)", description: "Original uploaded raw dataset filename" },
      { name: "file_hash_sha256", type: "VARCHAR(64)", description: "Tamper-evident evidentiary checksum" },
      { name: "status", type: "VARCHAR(24)", description: "READY | PROCESSING | COMPLETED | ERROR" },
      { name: "created_at", type: "TIMESTAMP", description: "Session initialization timestamp" }
    ],
    relationships: [
      "1:N with Transaction",
      "1:N with Analysis"
    ]
  }
];
